# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
name: Build Curity Plugin with Maven

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build & test with Maven
        run: mvn -B package --file pom.xml

      - name: Copy plugin jars
        run: mkdir staging && cp target/*.jar staging

      - name: Upload plugin artifacts
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jars
          path: staging

  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: create a new release
        run: echo "create new release using GitHub APIs"
